### ISSUE TITLE
Regarding computational power and training time

### ISSUE THREAD

**Issue by mradul2** [jianlong-yuan/SimpleBaseline#2]
Hello! Thank you for your code implementation.

It would be very helpful if you mention approximately how much time was required for the model training per experiment. And what computational devices were being used during the experiments (Number and type of GPU/TPU's). 

Looking forward to hearing from you soon.

**Comment by jianlong-yuan** [comment]
We counted the training time, about 4 hours or so of training. We used 8 GPUs, our GPU is Tesla V100. if you want to go even faster, please use fp16 for acceleration.
